authors:
- Ansible
dependencies: {}
description: Bulk test collection tnsb164e5.tc8cd2038a (based on ansible.utils)
license:
- GPL-2.0-or-later
name: tc8cd2038a
namespace: tnsb164e5
readme: README.md
repository: https://github.com/test/tnsb164e5.tc8cd2038a
tags:
- networking
version: 6.0.2
